services:
  - type: web
    name: telegram-management-bot
    env: python
    pythonVersion: "3.10"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "8190987979:AAGqLQxym3_45oM0W1hhwfl2t0XTM4ZUOT4"
      - key: ADMIN_ID
        value: "7282835498"
      - key: CHANNEL_ID
        value: "-1002678391495"
